FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY SimulationService/ ./SimulationService/
COPY DataBase/ ./DataBase/

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

CMD ["python", "SimulationService/consumer.py"]