services:

  db:
    image: postgres:16
    container_name: simulation-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: simulation-rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}

  api:
    #build:
    #  context: .
    #  dockerfile: Dockerfile.api
    image: ghcr.io/tostas17/simulator-api:latest
    container_name: simulation-api
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  simulation-worker:
    #build:
    #  context: .
    #  dockerfile: Dockerfile.worker
    image: ghcr.io/tostas17/simulator-worker:latest
    container_name: simulation-worker
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  websocket:
    #build:
    #  context: .
    #  dockerfile: Dockerfile.websocket
    image: ghcr.io/tostas17/simulator-websocket:latest
    container_name: simulation-websocket
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy

  nginx:
    #build: 
    #  context: .
    #  dockerfile: Dockerfile.nginx
    image: ghcr.io/tostas17/simulator-nginx:latest
    container_name: simulation-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api

  frontend:
    #build:
    #  context: .
    #  dockerfile: Dockerfile.frontend
    image: ghcr.io/tostas17/simulator-frontend:latest
    container_name: simulation-frontend

volumes:
  pgdata: