FROM node:20-alpine AS builder
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .
RUN npm run build

FROM node:20-alpine
RUN npm install -g serve
WORKDIR /app
COPY --from=builder /app/dist /app/dist

# the working directory is /app, and we serve the /app/dist folder
# the -s flag enables routing for SPAs (Single Page Applications)
CMD ["serve", "-s", "dist", "-l", "3000"]