events {
    worker_connections 1024;
}

http {
    # Includes standard file types (important for the Frontend)
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    
    server {
        listen 80;

        # The Frontend is served from the root
        location / {
            proxy_pass http://frontend:3000;
        }

        # API goes to the 'api' container on port 8000
        location /api/ {
            # The 'rewrite' removes the /api prefix before sending it to FastAPI
            rewrite ^/api/(.*) /$1 break;
            proxy_pass http://api:8000;
        }

        # WebSocket goes to the 'websocket' container on port 8000
        location /ws/ {
            proxy_pass http://websocket:8000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}